"""Tests for the per-patient amortized personalization.

These guard the CONTRACT, not the accuracy: that it refuses to personalize when
the history is too thin, that it never crashes the app, and above all that a
personalized projection is still generated by the mechanistic ODE.
"""
import os
import sys

import numpy as np
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
import model_core as core
import personalize as pz


def test_refuses_to_personalize_from_a_single_visit():
    """With one measurement there is nothing to personalize FROM. It must return
    the population parameters and say why -- not invent a personalization."""
    r = pz.personalize([0.0], [55.0], a1c=8.0, uacr0=300.0, sbp=145.0)
    assert r["personalized"] is False
    assert r["params"]["q"] == core.TRIAL_CALIBRATION_V2["q"]
    assert "population" in r["reason"]


def test_refuses_when_the_history_is_too_short_in_time():
    """Three measurements crammed into two months say nothing about a decade."""
    r = pz.personalize([0.0, 0.05, 0.1], [55.0, 54.0, 53.0],
                       a1c=8.0, uacr0=300.0, sbp=145.0)
    assert r["personalized"] is False


def test_a_stale_cache_is_retrained_not_fatal(monkeypatch):
    """A missing or version-incompatible cached estimator must be RETRAINED, not
    crash: the estimator is derived from simulations, so it is always recoverable."""
    def boom(*a, **k):
        raise FileNotFoundError("stale or missing pickle")
    monkeypatch.setattr(pz.Personalizer, "load", staticmethod(boom))
    pz._CACHE.clear()
    est = pz.get_estimator()
    assert est is not None and len(est.models) == pz.N_MODELS_DEFAULT


def test_a_broken_estimator_degrades_gracefully(monkeypatch):
    """If even training fails, the app must fall back to population parameters
    rather than crashing -- or, worse, pretending to personalize."""
    def boom(*a, **k):
        raise RuntimeError("cannot train here")
    monkeypatch.setattr(pz, "get_estimator", boom)
    r = pz.personalize([0.0, 1.5, 3.0], [70.0, 62.0, 55.0],
                       a1c=8.0, uacr0=300.0, sbp=145.0)
    assert r["personalized"] is False
    assert r["params"] == core.TRIAL_CALIBRATION_V2


def test_features_are_finite_and_fixed_size():
    f = pz.features([0.0, 1.0, 2.5], [80.0, 70.0, 58.0], 8.0, 300.0, 145.0)
    assert f.shape == (pz.N_FEATURES,)
    assert np.all(np.isfinite(f))
    # a single visit must not produce NaNs (no slope/curvature available)
    f1 = pz.features([0.0], [55.0], 8.0, 300.0, 145.0)
    assert np.all(np.isfinite(f1))


def test_patient_params_scale_the_hazard_not_the_structure():
    """Personalization rescales the injury rate; it must not silently change the
    model's structural constants (the saturation ceiling, beta, k0)."""
    base = core.TRIAL_CALIBRATION_V2
    p = pz.patient_params(q=2.0, scale=2.0)
    assert p["q"] == 2.0
    assert p["k_hf"] > base["k_hf"]
    assert p["s_sat"] == base["s_sat"]
    assert p["beta"] == base["beta"]
    assert p["k0"] == base["k0"]


def test_a_falling_patient_gets_a_worse_projection_than_a_flat_one():
    """The whole point: two patients with the SAME eGFR today but different pasts
    must get different futures."""
    kw = dict(a1c=8.0, uacr0=300.0, sbp=145.0)
    t = [0.0, 1.0, 2.0, 3.0]
    falling = pz.personalize(t, [85.0, 72.0, 63.0, 55.0], **kw)
    flat = pz.personalize(t, [58.0, 57.0, 56.0, 55.0], **kw)
    assert falling["personalized"] and flat["personalized"]
    assert falling["scale"] > flat["scale"]

    _, _, _, td_falling = core.simulate_trajectory_v2(55.0, 8.0, 300.0, 145.0, u=0.0,
                                                      p=falling["params"], years=20)
    _, _, _, td_flat = core.simulate_trajectory_v2(55.0, 8.0, 300.0, 145.0, u=0.0,
                                                   p=flat["params"], years=20)
    assert td_falling < td_flat
