"""
================================================================================
PER-PATIENT PERSONALIZATION  ·  amortized inference (NephroQ)
================================================================================
THE PROBLEM THIS SOLVES

The app is used one patient at a time, but until now every patient was projected
with the SAME population parameters (q, hazard scale) anchored to published
trials. Two patients with an identical eGFR today got an identical future — even
if one had been falling steeply for three years and the other was flat.

What actually differs between patients is *how fast their kidney is losing
nephrons* and *how abruptly the terminal collapse comes* — i.e. their personal
hazard scale and their personal feedback exponent q.

--------------------------------------------------------------------------------
THE APPROACH: amortized (simulation-based) inference

Classical route: for each new patient, run a nonlinear least-squares fit of the
ODE to their handful of measurements. That works, but it is slow, it needs a
per-patient optimizer that can get stuck, and with 3-4 noisy points it is
unstable.

Amortized route (what this module does):

    1. SIMULATE many virtual patients from the mechanistic model itself,
       drawing (q, scale) from a prior. No patient data is needed to train.
    2. For each, keep only what a clinic actually sees: a few noisy eGFR
       measurements at irregular times, plus HbA1c / UACR / SBP.
    3. TRAIN a neural network to invert that mapping:
           observations  ->  (q, scale)
    4. At run time, the network infers a NEW patient's parameters in
       microseconds, with no optimizer in the loop.

This is a HYBRID model, not a black box: the neural net solves only the INVERSE
problem. The forward projection is still the mechanistic ODE, and the network's
output is two physically meaningful numbers, not an opaque embedding. Whatever
the network says, the trajectory the patient sees is still generated by the
biology.

UNCERTAINTY: an ensemble of networks is trained on different bootstrap resamples
of the simulations. Their disagreement is the parameter uncertainty. With few
visits the ensemble disagrees a lot — which is the honest answer, and the app can
then fall back to population parameters.

--------------------------------------------------------------------------------
HONEST LIMITS

- Trained on simulations from OUR model, so it inherits every assumption the
  model makes. It infers "the parameters that best explain these points UNDER
  this model" -- not ground truth.
- It needs at least 2-3 eGFR measurements spanning enough time. With one visit
  there is nothing to personalize from, and the module says so and returns the
  population values instead of inventing a personalization.
- Measurement noise is assumed (sd ~6 mL/min/1.73m2, in line with the observed
  within-patient dispersion). If a cohort is noisier, retrain with a larger sd.

Usage:
    python personalize.py --train      # train + validate, saves the estimator
    python personalize.py              # validate a previously trained estimator
================================================================================
"""
import os
import pickle
import argparse
import warnings

import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler

import model_core as core

warnings.filterwarnings("ignore", category=UserWarning)

HERE = os.path.dirname(os.path.abspath(__file__))
# The trained estimator is a CACHE, not an artifact of the repository: it is
# derived entirely from simulations of the mechanistic model, so it can always be
# regenerated. It is therefore git-ignored and trained on first use (~13 s),
# rather than committing a binary blob that would also break whenever scikit-learn
# changes its pickle format.
MODEL_PATH = os.path.join(HERE, "..", "calibration", "personalizer.pkl")

# Training configuration. Chosen by measuring the cost/accuracy trade-off:
# 2500 sims with (96,48) nets trains in ~13 s and forecasts at RMSE 9.60, versus
# 9.45 for a 4000-sim/(128,64) model that takes ~29 s. Halving it again to 1500
# sims does hurt (RMSE 11.58), so this is the knee of the curve.
N_TRAIN_DEFAULT = 2500
HIDDEN_DEFAULT = (96, 48)
N_MODELS_DEFAULT = 4

# ---- priors over the two PERSONAL parameters ---------------------------------
# q      : how abrupt the terminal collapse is (population value: 1.52)
# scale  : this patient's overall injury rate, as a multiple of the population one
Q_RANGE = (0.8, 2.6)
SCALE_RANGE = (0.25, 3.0)      # log-uniform
MEAS_NOISE_SD = 6.0            # mL/min/1.73m2, per measurement

N_FEATURES = 11


def patient_params(q, scale):
    """A personal parameter set = the trial-anchored population model, rescaled."""
    p = dict(core.TRIAL_CALIBRATION_V2)
    base_k, base_w = 0.0141 * 0.730, np.array([0.0144, 0.0180, 0.0108]) * 0.730
    p.update(q=float(q),
             k_hf=float(base_k * scale),
             w_a1c=float(base_w[0] * scale),
             w_uacr=float(base_w[1] * scale),
             w_sbp=float(base_w[2] * scale))
    return p


def features(t, egfr, a1c, uacr0, sbp):
    """
    Fixed-size summary of what a clinic actually has on a patient.

    Deliberately simple and interpretable: level, trend, curvature, scatter,
    how much follow-up there is, and the metabolic covariates. The network's job
    is to map these to (q, scale); it is not asked to learn the biology, which
    the ODE already encodes.
    """
    t = np.asarray(t, float)
    e = np.asarray(egfr, float)
    n = len(t)
    span = float(t[-1] - t[0]) if n > 1 else 0.0

    if n >= 2 and span > 0:
        slope, intercept = np.polyfit(t, e, 1)
        resid = e - (slope * t + intercept)
        scatter = float(np.std(resid))
    else:
        slope, scatter = 0.0, 0.0
    if n >= 3 and span > 0:
        curv = float(np.polyfit(t, e, 2)[0])     # >0 = decelerating, <0 = accelerating
    else:
        curv = 0.0

    return np.array([
        e[0],                       # baseline eGFR
        e[-1],                      # latest eGFR
        float(np.mean(e)),
        slope,                      # observed decline rate
        curv,                       # observed curvature -- the signal for q
        scatter,
        span,
        float(n),
        a1c,
        float(np.log1p(uacr0 / 30.0)),
        sbp,
    ], dtype=float)


def simulate_training_set(n_patients=8000, seed=0):
    """Draw virtual patients from the mechanistic model and record what a clinic
    would have seen: a few noisy eGFR values at irregular times."""
    rng = np.random.default_rng(seed)
    X, Y = [], []
    for _ in range(n_patients):
        q = rng.uniform(*Q_RANGE)
        scale = float(np.exp(rng.uniform(np.log(SCALE_RANGE[0]), np.log(SCALE_RANGE[1]))))
        egfr0 = rng.uniform(20.0, 110.0)
        a1c = rng.uniform(5.5, 12.0)
        uacr0 = float(np.exp(rng.uniform(np.log(5.0), np.log(3000.0))))
        sbp = rng.uniform(105.0, 185.0)

        n_visits = rng.integers(2, 9)
        span = rng.uniform(0.8, 6.0)
        t_obs = np.sort(rng.uniform(0, span, n_visits))
        t_obs[0] = 0.0

        p = patient_params(q, scale)
        t, egfr, _, _ = core.simulate_trajectory_v2(egfr0, a1c, uacr0, sbp, u=0.0,
                                                    p=p, years=max(span, 0.5), n=120)
        e_true = np.interp(t_obs, t, egfr)
        e_obs = e_true + rng.normal(0, MEAS_NOISE_SD, len(t_obs))
        e_obs = np.clip(e_obs, 3.0, None)

        X.append(features(t_obs, e_obs, a1c, uacr0, sbp))
        Y.append([q, np.log(scale)])          # predict log-scale (it is log-uniform)
    return np.array(X), np.array(Y)


class Personalizer:
    """Ensemble of small MLPs. Their disagreement IS the uncertainty."""

    def __init__(self, n_models=N_MODELS_DEFAULT, hidden=HIDDEN_DEFAULT, seed=0):
        self.n_models, self.hidden, self.seed = n_models, hidden, seed
        self.scaler, self.models = None, []

    def fit(self, X, Y):
        self.scaler = StandardScaler().fit(X)
        Xs = self.scaler.transform(X)
        rng = np.random.default_rng(self.seed)
        self.models = []
        for i in range(self.n_models):
            idx = rng.integers(0, len(Xs), len(Xs))       # bootstrap resample
            m = MLPRegressor(hidden_layer_sizes=self.hidden, activation="relu",
                             max_iter=600, early_stopping=True, n_iter_no_change=20,
                             random_state=self.seed + i)
            m.fit(Xs[idx], Y[idx])
            self.models.append(m)
        return self

    def predict(self, X):
        """Returns (q_mean, q_sd, scale_mean, scale_sd)."""
        Xs = self.scaler.transform(np.atleast_2d(X))
        P = np.stack([m.predict(Xs) for m in self.models])     # (n_models, n, 2)
        q = np.clip(P[:, :, 0], *Q_RANGE)
        scale = np.exp(P[:, :, 1])
        return (q.mean(0), q.std(0), scale.mean(0), scale.std(0))

    def save(self, path=MODEL_PATH):
        # Pickle the COMPONENTS, not `self`. Pickling the instance records the
        # class as `__main__.Personalizer` when this file is run as a script,
        # which then fails to unpickle from anywhere else (e.g. the app).
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as f:
            pickle.dump(dict(scaler=self.scaler, models=self.models,
                             n_models=self.n_models, hidden=self.hidden,
                             seed=self.seed), f)

    @staticmethod
    def load(path=MODEL_PATH):
        with open(path, "rb") as f:
            d = pickle.load(f)
        est = Personalizer(n_models=d["n_models"], hidden=d["hidden"], seed=d["seed"])
        est.scaler, est.models = d["scaler"], d["models"]
        return est


# ------------------------------------------------------------------------------
# Train-on-demand
# ------------------------------------------------------------------------------
def train(n_train=N_TRAIN_DEFAULT, seed=0, save=True, verbose=False):
    """Simulate virtual patients from the mechanistic model and fit the estimator."""
    if verbose:
        print(f"Simulating {n_train} virtual patients from the mechanistic model...")
    X, Y = simulate_training_set(n_train, seed=seed)
    if verbose:
        print(f"Training the amortized estimator "
              f"(ensemble of {N_MODELS_DEFAULT} MLPs)...")
    est = Personalizer(seed=seed).fit(X, Y)
    if save:
        try:
            est.save()
        except Exception:
            pass          # a read-only filesystem must not be fatal
    return est


_CACHE = {}


def get_estimator(force_retrain=False):
    """
    Return the estimator, training it if necessary.

    Order: in-process cache -> on-disk cache -> train from scratch (~13 s).
    Nothing here is committed to the repository: the estimator is derived purely
    from simulations of the mechanistic model, so it is always reproducible.
    """
    if not force_retrain and "est" in _CACHE:
        return _CACHE["est"]
    if not force_retrain:
        try:
            _CACHE["est"] = Personalizer.load()
            return _CACHE["est"]
        except Exception:
            pass          # missing, or a stale pickle from another sklearn version
    _CACHE["est"] = train()
    return _CACHE["est"]


MIN_VISITS = 3
MIN_SPAN_YEARS = 0.75


def personalize(t, egfr, a1c, uacr0, sbp, estimator=None):
    """
    Infer this patient's (q, scale) from their measurement history.

    Returns a dict with the parameter set to project with, plus a `personalized`
    flag and a human-readable reason. If the history is too thin to say anything,
    it does NOT invent a personalization: it returns the population parameters and
    says why.
    """
    t = np.asarray(t, float)
    egfr = np.asarray(egfr, float)
    span = float(t[-1] - t[0]) if len(t) > 1 else 0.0

    if len(t) < MIN_VISITS or span < MIN_SPAN_YEARS:
        return dict(personalized=False,
                    reason=f"needs >={MIN_VISITS} eGFR measurements spanning "
                           f">={MIN_SPAN_YEARS} years; using population parameters",
                    params=dict(core.TRIAL_CALIBRATION_V2), q=None, q_sd=None,
                    scale=None, scale_sd=None)

    if estimator is None:
        try:
            estimator = get_estimator()      # loads the cache, or trains (~13 s)
        except Exception:
            # Training or loading must NEVER break the app: fall back to the
            # population parameters and say so, rather than crashing or -- worse --
            # silently pretending to personalize.
            return dict(personalized=False,
                        reason="personalizer unavailable; using population parameters",
                        params=dict(core.TRIAL_CALIBRATION_V2), q=None, q_sd=None,
                        scale=None, scale_sd=None)
    est = estimator
    q, q_sd, scale, scale_sd = est.predict(features(t, egfr, a1c, uacr0, sbp))
    q, q_sd, scale, scale_sd = float(q[0]), float(q_sd[0]), float(scale[0]), float(scale_sd[0])

    return dict(personalized=True, reason="inferred from this patient's history",
                params=patient_params(q, scale),
                q=q, q_sd=q_sd, scale=scale, scale_sd=scale_sd)


# ------------------------------------------------------------------------------
# Validation -- the estimator has to EARN its place
# ------------------------------------------------------------------------------
def least_squares_baseline(t, egfr, a1c, uacr0, sbp):
    """The classical alternative: fit (q, scale) per patient with an optimizer.
    This is the rival the network has to beat -- on accuracy or on speed."""
    from scipy.optimize import least_squares

    def resid(z):
        q = np.clip(z[0], *Q_RANGE)
        scale = float(np.exp(np.clip(z[1], np.log(SCALE_RANGE[0]), np.log(SCALE_RANGE[1]))))
        p = patient_params(q, scale)
        pred = core.predict_egfr_at_v2(egfr[0], a1c, uacr0, sbp, 0.0, p, t,
                                       years=max(float(t[-1]), 0.5))
        return pred - egfr

    sol = least_squares(resid, [1.5, 0.0], method="lm", max_nfev=200)
    q = float(np.clip(sol.x[0], *Q_RANGE))
    scale = float(np.exp(np.clip(sol.x[1], np.log(SCALE_RANGE[0]), np.log(SCALE_RANGE[1]))))
    return q, scale


def validate(est, n_test=400, seed=999, horizon=5.0):
    """
    Two questions, both of which the estimator can fail:
      1. Does it RECOVER the parameters it was asked to infer?
      2. Does personalizing actually FORECAST better than population parameters
         -- and how does it compare to the classical least-squares fit?
    """
    import time
    rng = np.random.default_rng(seed)
    rows = []
    for _ in range(n_test):
        q_true = rng.uniform(*Q_RANGE)
        scale_true = float(np.exp(rng.uniform(np.log(SCALE_RANGE[0]), np.log(SCALE_RANGE[1]))))
        egfr0 = rng.uniform(25.0, 100.0)
        a1c = rng.uniform(6.0, 11.0)
        uacr0 = float(np.exp(rng.uniform(np.log(10.0), np.log(2000.0))))
        sbp = rng.uniform(110.0, 175.0)

        span = rng.uniform(2.0, 5.0)
        n_visits = rng.integers(3, 8)
        t_obs = np.sort(rng.uniform(0, span, n_visits)); t_obs[0] = 0.0

        p_true = patient_params(q_true, scale_true)
        t, egfr, _, _ = core.simulate_trajectory_v2(egfr0, a1c, uacr0, sbp, u=0.0,
                                                    p=p_true, years=span + horizon, n=200)
        e_obs = np.interp(t_obs, t, egfr) + rng.normal(0, MEAS_NOISE_SD, n_visits)
        e_obs = np.clip(e_obs, 3.0, None)
        e_future_true = float(np.interp(span + horizon, t, egfr))     # the held-out future

        # --- 1. amortized network
        t0 = time.perf_counter()
        q_hat, _, s_hat, _ = est.predict(features(t_obs, e_obs, a1c, uacr0, sbp))
        t_nn = time.perf_counter() - t0
        q_hat, s_hat = float(q_hat[0]), float(s_hat[0])

        # --- 2. classical per-patient least squares
        t0 = time.perf_counter()
        q_ls, s_ls = least_squares_baseline(t_obs, e_obs, a1c, uacr0, sbp)
        t_ls = time.perf_counter() - t0

        def forecast(q, scale):
            p = patient_params(q, scale)
            return float(core.predict_egfr_at_v2(e_obs[0], a1c, uacr0, sbp, 0.0, p,
                                                 np.array([span + horizon]),
                                                 years=span + horizon)[0])

        rows.append(dict(
            q_true=q_true, q_nn=q_hat, q_ls=q_ls,
            scale_true=scale_true, scale_nn=s_hat, scale_ls=s_ls,
            e_true=e_future_true,
            e_nn=forecast(q_hat, s_hat),
            e_ls=forecast(q_ls, s_ls),
            e_pop=forecast(core.TRIAL_CALIBRATION_V2["q"], 1.0),
            t_nn=t_nn, t_ls=t_ls,
        ))

    import pandas as pd
    df = pd.DataFrame(rows)

    def r2(a, b):
        return 1 - np.sum((a - b) ** 2) / np.sum((a - np.mean(a)) ** 2)

    def rmse(a, b):
        return float(np.sqrt(np.mean((a - b) ** 2)))

    print("\n" + "=" * 74)
    print("VALIDATION -- held-out virtual patients (n=%d)" % len(df))
    print("=" * 74)
    print("\n1) PARAMETER RECOVERY (can it infer what it was asked to infer?)")
    print(f"   {'':10}{'network':>12}{'least-squares':>16}")
    print(f"   {'q  (R2)':10}{r2(df.q_true, df.q_nn):12.3f}{r2(df.q_true, df.q_ls):16.3f}")
    print(f"   {'scale (R2)':10}{r2(df.scale_true, df.scale_nn):12.3f}"
          f"{r2(df.scale_true, df.scale_ls):16.3f}")

    print(f"\n2) FORECAST at +{horizon:.0f} years beyond the last visit (mL/min/1.73m2)")
    pop, nn, ls = rmse(df.e_true, df.e_pop), rmse(df.e_true, df.e_nn), rmse(df.e_true, df.e_ls)
    print(f"   {'population parameters (current app)':<38}RMSE {pop:6.2f}")
    print(f"   {'amortized network (personalized)':<38}RMSE {nn:6.2f}   "
          f"({100*(1-nn/pop):+.0f}% vs population)")
    print(f"   {'per-patient least squares':<38}RMSE {ls:6.2f}   "
          f"({100*(1-ls/pop):+.0f}% vs population)")

    print(f"\n3) SPEED per patient")
    print(f"   network        {1000*df.t_nn.mean():7.2f} ms")
    print(f"   least squares  {1000*df.t_ls.mean():7.2f} ms   "
          f"({df.t_ls.mean()/max(df.t_nn.mean(),1e-9):.0f}x slower)")

    verdict = "EARNS ITS PLACE" if nn < pop else "DOES NOT BEAT POPULATION PARAMETERS"
    print(f"\n>>> {verdict}")
    return df


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Per-patient amortized personalization")
    ap.add_argument("--train", action="store_true")
    ap.add_argument("--n-train", type=int, default=N_TRAIN_DEFAULT)
    ap.add_argument("--n-test", type=int, default=300)
    a = ap.parse_args()

    est = train(n_train=a.n_train, verbose=True) if a.train else get_estimator()
    validate(est, n_test=a.n_test)
